---
name: Container image build
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out proper version of sources
        uses: actions/checkout@v1

      - name: Install token for quay
        env:
          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
        run: |
          echo "$QUAY_TOKEN" | docker login --username machacekondra+github --password-stdin

      - name: Build & push the container image to quay
        run: |
          make deploy-container-image
